## NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [ ]:
type(mylist)

list

In [ ]:
# To transform something into NumPy array
np.array(mylist)

array([1, 2, 3])

In [ ]:
# mylist is still just a normal Python list
mylist

[1, 2, 3]

In [ ]:
type(mylist)

list

In [ ]:
#we have to reassign it to smth like myarr
myarr = np.array(mylist)

In [ ]:
myarr

array([1, 2, 3])

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
#nested list in python
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# built-in functions: this is equivalent in NumPy to python's range function.
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5)) # 2 raws by 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#it returns evenly spaced numbers over a specified interval.
np.linspace(0,10,11)
#going from 0 to 10, give me three linearly spaced or evenly spaced numbers over that interval

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,2)

array([[0.26756531, 0.35575813],
       [0.45810133, 0.16206992],
       [0.89489939, 0.58424032],
       [0.31409967, 0.53736165],
       [0.34511811, 0.8839735 ]])

In [ ]:
np.random.randn(5)

array([ 0.01658092, -0.62007648, -0.18243498, -0.21970659, -0.41271841])

In [ ]:
np.random.randn(5,2)

array([[-1.79896837, -3.12684763],
       [ 1.99367497, -0.14232248],
       [-1.25432044, -0.34885077],
       [ 0.02829   , -0.16646009],
       [ 0.19682268, -2.43733912]])

In [ ]:
#returns back random integers
#5 random integers(0,101,5)
#give this to me but in the shape of a four by five array. (0,101,(4,5))
np.random.randint(0,101,(4,5))

array([[75, 17,  3, 64,  1],
       [98, 82, 30, 37, 62],
       [75, 86, 45, 75, 88],
       [34, 54, 77,  9, 89]])

In [ ]:
# seed allows us to do is set a particular set of numbers
# for being able to repeat random distributions in order to test different models on them
# or test different visualization models
# 42 is arbitrary choice
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
#couple of useful attributes and method calls
arr =np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr = np.random.randint(0,101,10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [ ]:
ranarr.max()

np.int64(99)

In [ ]:
ranarr.min()

np.int64(2)

In [ ]:
#index location
ranarr.argmax() #parentez varsa methoddur.

np.int64(5)

In [ ]:
ranarr.dtype #attribute

dtype('int64')

In [ ]:
arr.shape #attribute

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(5, 5)