In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr #I have numbers 0 through 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#I wanted just select a single value
arr[8]

np.int64(8)

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
#lets reset this
arr = np.arange(0,11)

In [ ]:
#slicing a section of an array and setting it to a new variable will actualy only act as a pointer to the original array.
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#everything is set to 99
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
#if you wanted to not have it affect the original array, you would need to explicitly set a copy
arr_copy = arr.copy() #copy method
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr #original did not change

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

#### Create a two-dimensional array

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#this returns back the number of rows first, then number of columns (3,3)
arr_2d.shape

(3, 3)

In [ ]:
# I want to grab a single row
arr_2d[0]

array([ 5, 10, 15])

In [ ]:
#I want to grab a single element value
arr_2d[1,1] #row 1, column 1

np.int64(25)

In [ ]:
arr_2d[:2] #up to but not including row 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Conditional Selection

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# I can broadcast a condition or a comparison off of this.
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])